call pyuic4 -o qad_ui.py qad.ui
call pyuic4 -o qad_dsettings_ui.py qad_dsettings.ui
call pyuic4 -o qad_dimstyle_ui.py qad_dimstyle.ui
call pyuic4 -o qad_dimstyle_details_ui.py qad_dimstyle_details.ui
call pyuic4 -o qad_dimstyle_new_ui.py qad_dimstyle_new.ui
call pyuic4 -o qad_dimstyle_diff_ui.py qad_dimstyle_diff.ui
call pyuic4 -o qad_options_ui.py qad_options.ui
call pyuic4 -o qad_gripcolor_ui.py qad_gripcolor.ui
call pyuic4 -o qad_windowcolor_ui.py qad_windowcolor.ui