# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qad_dimstyle_details.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DimStyle_Details_Dialog(object):
    def setupUi(self, DimStyle_Details_Dialog):
        DimStyle_Details_Dialog.setObjectName("DimStyle_Details_Dialog")
        DimStyle_Details_Dialog.resize(637, 446)
        DimStyle_Details_Dialog.setMinimumSize(QtCore.QSize(600, 446))
        DimStyle_Details_Dialog.setMaximumSize(QtCore.QSize(700, 446))
        self.tabWidget = QtWidgets.QTabWidget(DimStyle_Details_Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 621, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.DBTab = QtWidgets.QWidget()
        self.DBTab.setObjectName("DBTab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.DBTab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 291, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(12, 20, 81, 21))
        self.label_2.setObjectName("label_2")
        self.linearLayerName = QtWidgets.QComboBox(self.groupBox_5)
        self.linearLayerName.setGeometry(QtCore.QRect(100, 20, 181, 22))
        self.linearLayerName.setObjectName("linearLayerName")
        self.lineTypeFieldName = QtWidgets.QComboBox(self.groupBox_5)
        self.lineTypeFieldName.setGeometry(QtCore.QRect(140, 50, 141, 22))
        self.lineTypeFieldName.setObjectName("lineTypeFieldName")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_21.setObjectName("label_21")
        self.groupBox_6 = QtWidgets.QGroupBox(self.DBTab)
        self.groupBox_6.setGeometry(QtCore.QRect(9, 100, 291, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.symbolLayerName = QtWidgets.QComboBox(self.groupBox_6)
        self.symbolLayerName.setGeometry(QtCore.QRect(100, 20, 181, 22))
        self.symbolLayerName.setObjectName("symbolLayerName")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_13.setObjectName("label_13")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_22.setObjectName("label_22")
        self.symbolFieldName = QtWidgets.QComboBox(self.groupBox_6)
        self.symbolFieldName.setGeometry(QtCore.QRect(140, 50, 141, 22))
        self.symbolFieldName.setObjectName("symbolFieldName")
        self.scaleFieldName = QtWidgets.QComboBox(self.groupBox_6)
        self.scaleFieldName.setGeometry(QtCore.QRect(140, 80, 141, 22))
        self.scaleFieldName.setObjectName("scaleFieldName")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_23.setObjectName("label_23")
        self.groupBox_7 = QtWidgets.QGroupBox(self.DBTab)
        self.groupBox_7.setGeometry(QtCore.QRect(330, 220, 271, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.label_24.setObjectName("label_24")
        self.rotFieldName = QtWidgets.QComboBox(self.groupBox_7)
        self.rotFieldName.setGeometry(QtCore.QRect(120, 50, 141, 22))
        self.rotFieldName.setObjectName("rotFieldName")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_16.setObjectName("label_16")
        self.colorFieldName = QtWidgets.QComboBox(self.groupBox_7)
        self.colorFieldName.setGeometry(QtCore.QRect(120, 20, 141, 22))
        self.colorFieldName.setObjectName("colorFieldName")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(10, 110, 101, 21))
        self.label_28.setObjectName("label_28")
        self.idParentFieldName = QtWidgets.QComboBox(self.groupBox_7)
        self.idParentFieldName.setGeometry(QtCore.QRect(120, 110, 141, 22))
        self.idParentFieldName.setObjectName("idParentFieldName")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.label_25.setObjectName("label_25")
        self.componentFieldName = QtWidgets.QComboBox(self.groupBox_7)
        self.componentFieldName.setGeometry(QtCore.QRect(120, 80, 141, 22))
        self.componentFieldName.setObjectName("componentFieldName")
        self.groupBox_8 = QtWidgets.QGroupBox(self.DBTab)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 220, 291, 141))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_27.setObjectName("label_27")
        self.idFieldName = QtWidgets.QComboBox(self.groupBox_8)
        self.idFieldName.setGeometry(QtCore.QRect(140, 50, 141, 22))
        self.idFieldName.setObjectName("idFieldName")
        self.dimStyleFieldName = QtWidgets.QComboBox(self.groupBox_8)
        self.dimStyleFieldName.setGeometry(QtCore.QRect(140, 80, 141, 22))
        self.dimStyleFieldName.setObjectName("dimStyleFieldName")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        self.label_30.setGeometry(QtCore.QRect(10, 110, 121, 21))
        self.label_30.setObjectName("label_30")
        self.dimTypeFieldName = QtWidgets.QComboBox(self.groupBox_8)
        self.dimTypeFieldName.setGeometry(QtCore.QRect(140, 110, 141, 22))
        self.dimTypeFieldName.setObjectName("dimTypeFieldName")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_14.setObjectName("label_14")
        self.textualLayerName = QtWidgets.QComboBox(self.groupBox_8)
        self.textualLayerName.setGeometry(QtCore.QRect(100, 20, 181, 22))
        self.textualLayerName.setObjectName("textualLayerName")
        self.previewDummy = QtWidgets.QPushButton(self.DBTab)
        self.previewDummy.setGeometry(QtCore.QRect(340, 20, 251, 181))
        self.previewDummy.setText("")
        self.previewDummy.setObjectName("previewDummy")
        self.tabWidget.addTab(self.DBTab, "")
        self.LineTab = QtWidgets.QWidget()
        self.LineTab.setObjectName("LineTab")
        self.groupBox = QtWidgets.QGroupBox(self.LineTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label.setObjectName("label")
        self.dimLineLineType = QtWidgets.QLineEdit(self.groupBox)
        self.dimLineLineType.setGeometry(QtCore.QRect(90, 50, 171, 20))
        self.dimLineLineType.setObjectName("dimLineLineType")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_5.setObjectName("label_5")
        self.dimLine1Hide = QtWidgets.QCheckBox(self.groupBox)
        self.dimLine1Hide.setGeometry(QtCore.QRect(70, 110, 91, 21))
        self.dimLine1Hide.setObjectName("dimLine1Hide")
        self.dimLine2Hide = QtWidgets.QCheckBox(self.groupBox)
        self.dimLine2Hide.setGeometry(QtCore.QRect(170, 110, 91, 21))
        self.dimLine2Hide.setObjectName("dimLine2Hide")
        self.dimLineColorDummy = QtWidgets.QPushButton(self.groupBox)
        self.dimLineColorDummy.setGeometry(QtCore.QRect(90, 20, 171, 23))
        self.dimLineColorDummy.setText("")
        self.dimLineColorDummy.setObjectName("dimLineColorDummy")
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(10, 80, 161, 21))
        self.label_41.setObjectName("label_41")
        self.dimLineOffsetExtLine = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dimLineOffsetExtLine.setGeometry(QtCore.QRect(180, 80, 81, 22))
        self.dimLineOffsetExtLine.setDecimals(6)
        self.dimLineOffsetExtLine.setMaximum(1000000.0)
        self.dimLineOffsetExtLine.setSingleStep(0.0005)
        self.dimLineOffsetExtLine.setObjectName("dimLineOffsetExtLine")
        self.groupBox_2 = QtWidgets.QGroupBox(self.LineTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 591, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(11, 20, 81, 21))
        self.label_6.setObjectName("label_6")
        self.extLine1LineType = QtWidgets.QLineEdit(self.groupBox_2)
        self.extLine1LineType.setGeometry(QtCore.QRect(130, 50, 161, 20))
        self.extLine1LineType.setObjectName("extLine1LineType")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_8.setObjectName("label_8")
        self.extLine2LineType = QtWidgets.QLineEdit(self.groupBox_2)
        self.extLine2LineType.setGeometry(QtCore.QRect(130, 80, 161, 20))
        self.extLine2LineType.setObjectName("extLine2LineType")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_9.setObjectName("label_9")
        self.extLine1Hide = QtWidgets.QCheckBox(self.groupBox_2)
        self.extLine1Hide.setGeometry(QtCore.QRect(80, 110, 101, 21))
        self.extLine1Hide.setObjectName("extLine1Hide")
        self.extLine2Hide = QtWidgets.QCheckBox(self.groupBox_2)
        self.extLine2Hide.setGeometry(QtCore.QRect(190, 110, 101, 21))
        self.extLine2Hide.setObjectName("extLine2Hide")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(310, 20, 181, 21))
        self.label_10.setObjectName("label_10")
        self.extLineOffsetDimLine = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.extLineOffsetDimLine.setGeometry(QtCore.QRect(500, 20, 81, 22))
        self.extLineOffsetDimLine.setDecimals(6)
        self.extLineOffsetDimLine.setMaximum(1000000.0)
        self.extLineOffsetDimLine.setSingleStep(0.0005)
        self.extLineOffsetDimLine.setObjectName("extLineOffsetDimLine")
        self.extLineOffsetOrigPoints = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.extLineOffsetOrigPoints.setGeometry(QtCore.QRect(500, 50, 81, 22))
        self.extLineOffsetOrigPoints.setDecimals(6)
        self.extLineOffsetOrigPoints.setMaximum(1000000.0)
        self.extLineOffsetOrigPoints.setSingleStep(0.0005)
        self.extLineOffsetOrigPoints.setObjectName("extLineOffsetOrigPoints")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(310, 50, 181, 21))
        self.label_11.setObjectName("label_11")
        self.extLineIsFixedLen = QtWidgets.QCheckBox(self.groupBox_2)
        self.extLineIsFixedLen.setGeometry(QtCore.QRect(310, 80, 271, 21))
        self.extLineIsFixedLen.setObjectName("extLineIsFixedLen")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(310, 110, 181, 21))
        self.label_12.setObjectName("label_12")
        self.extLineFixedLen = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.extLineFixedLen.setGeometry(QtCore.QRect(500, 110, 81, 22))
        self.extLineFixedLen.setDecimals(6)
        self.extLineFixedLen.setMaximum(1000000.0)
        self.extLineFixedLen.setSingleStep(0.0005)
        self.extLineFixedLen.setObjectName("extLineFixedLen")
        self.extLineColorDummy = QtWidgets.QPushButton(self.groupBox_2)
        self.extLineColorDummy.setGeometry(QtCore.QRect(110, 20, 181, 23))
        self.extLineColorDummy.setText("")
        self.extLineColorDummy.setObjectName("extLineColorDummy")
        self.tabWidget.addTab(self.LineTab, "")
        self.SymbolTab = QtWidgets.QWidget()
        self.SymbolTab.setObjectName("SymbolTab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.SymbolTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 271, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.block1Name = QtWidgets.QLineEdit(self.groupBox_3)
        self.block1Name.setGeometry(QtCore.QRect(110, 20, 151, 20))
        self.block1Name.setObjectName("block1Name")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_15.setObjectName("label_15")
        self.block2Name = QtWidgets.QLineEdit(self.groupBox_3)
        self.block2Name.setGeometry(QtCore.QRect(110, 50, 151, 20))
        self.block2Name.setObjectName("block2Name")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_18.setObjectName("label_18")
        self.blockLeaderName = QtWidgets.QLineEdit(self.groupBox_3)
        self.blockLeaderName.setGeometry(QtCore.QRect(110, 80, 151, 20))
        self.blockLeaderName.setObjectName("blockLeaderName")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_19.setObjectName("label_19")
        self.blockWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.blockWidth.setGeometry(QtCore.QRect(180, 110, 81, 22))
        self.blockWidth.setDecimals(6)
        self.blockWidth.setMaximum(1000000.0)
        self.blockWidth.setSingleStep(0.0005)
        self.blockWidth.setObjectName("blockWidth")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 111, 21))
        self.label_17.setObjectName("label_17")
        self.blockScale = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.blockScale.setGeometry(QtCore.QRect(180, 140, 81, 22))
        self.blockScale.setDecimals(6)
        self.blockScale.setMaximum(1000000.0)
        self.blockScale.setSingleStep(0.0005)
        self.blockScale.setObjectName("blockScale")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 140, 111, 21))
        self.label_20.setObjectName("label_20")
        self.groupBox_4 = QtWidgets.QGroupBox(self.SymbolTab)
        self.groupBox_4.setGeometry(QtCore.QRect(350, 220, 231, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.arcSymbolPreceding = QtWidgets.QRadioButton(self.groupBox_4)
        self.arcSymbolPreceding.setGeometry(QtCore.QRect(10, 20, 211, 17))
        self.arcSymbolPreceding.setObjectName("arcSymbolPreceding")
        self.arcSymbolAbove = QtWidgets.QRadioButton(self.groupBox_4)
        self.arcSymbolAbove.setGeometry(QtCore.QRect(10, 40, 211, 17))
        self.arcSymbolAbove.setObjectName("arcSymbolAbove")
        self.arcSymbolNone = QtWidgets.QRadioButton(self.groupBox_4)
        self.arcSymbolNone.setGeometry(QtCore.QRect(10, 60, 211, 17))
        self.arcSymbolNone.setObjectName("arcSymbolNone")
        self.groupBox_11 = QtWidgets.QGroupBox(self.SymbolTab)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 190, 271, 81))
        self.groupBox_11.setObjectName("groupBox_11")
        self.centerMarkNone = QtWidgets.QRadioButton(self.groupBox_11)
        self.centerMarkNone.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.centerMarkNone.setObjectName("centerMarkNone")
        self.centerMarkMark = QtWidgets.QRadioButton(self.groupBox_11)
        self.centerMarkMark.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.centerMarkMark.setObjectName("centerMarkMark")
        self.centerMarkLine = QtWidgets.QRadioButton(self.groupBox_11)
        self.centerMarkLine.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.centerMarkLine.setObjectName("centerMarkLine")
        self.centerMarkLength = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.centerMarkLength.setGeometry(QtCore.QRect(180, 30, 81, 22))
        self.centerMarkLength.setDecimals(6)
        self.centerMarkLength.setMaximum(1000000.0)
        self.centerMarkLength.setSingleStep(0.0005)
        self.centerMarkLength.setObjectName("centerMarkLength")
        self.tabWidget.addTab(self.SymbolTab, "")
        self.TextTab = QtWidgets.QWidget()
        self.TextTab.setObjectName("TextTab")
        self.groupBox_9 = QtWidgets.QGroupBox(self.TextTab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 271, 111))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_26.setObjectName("label_26")
        self.textHeight = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.textHeight.setGeometry(QtCore.QRect(180, 80, 81, 22))
        self.textHeight.setDecimals(6)
        self.textHeight.setMaximum(1000000.0)
        self.textHeight.setSingleStep(0.0005)
        self.textHeight.setObjectName("textHeight")
        self.label_40 = QtWidgets.QLabel(self.groupBox_9)
        self.label_40.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_40.setObjectName("label_40")
        self.textFont = QtWidgets.QFontComboBox(self.groupBox_9)
        self.textFont.setGeometry(QtCore.QRect(100, 20, 161, 22))
        self.textFont.setObjectName("textFont")
        self.textColorDummy = QtWidgets.QPushButton(self.groupBox_9)
        self.textColorDummy.setGeometry(QtCore.QRect(80, 50, 181, 23))
        self.textColorDummy.setText("")
        self.textColorDummy.setObjectName("textColorDummy")
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_4.setObjectName("label_4")
        self.groupBox_10 = QtWidgets.QGroupBox(self.TextTab)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 220, 291, 141))
        self.groupBox_10.setObjectName("groupBox_10")
        self.textVerticalPos = QtWidgets.QComboBox(self.groupBox_10)
        self.textVerticalPos.setGeometry(QtCore.QRect(120, 20, 161, 22))
        self.textVerticalPos.setObjectName("textVerticalPos")
        self.label_31 = QtWidgets.QLabel(self.groupBox_10)
        self.label_31.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_10)
        self.label_32.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.label_32.setObjectName("label_32")
        self.textHorizontalPos = QtWidgets.QComboBox(self.groupBox_10)
        self.textHorizontalPos.setGeometry(QtCore.QRect(120, 50, 161, 22))
        self.textHorizontalPos.setObjectName("textHorizontalPos")
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.label_33.setObjectName("label_33")
        self.textDirection = QtWidgets.QComboBox(self.groupBox_10)
        self.textDirection.setGeometry(QtCore.QRect(120, 80, 161, 22))
        self.textDirection.setObjectName("textDirection")
        self.textOffsetDist = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.textOffsetDist.setGeometry(QtCore.QRect(200, 110, 81, 22))
        self.textOffsetDist.setDecimals(6)
        self.textOffsetDist.setMaximum(1000000.0)
        self.textOffsetDist.setSingleStep(0.0005)
        self.textOffsetDist.setObjectName("textOffsetDist")
        self.label_34 = QtWidgets.QLabel(self.groupBox_10)
        self.label_34.setGeometry(QtCore.QRect(10, 110, 181, 21))
        self.label_34.setObjectName("label_34")
        self.textAlignment_groupBox = QtWidgets.QGroupBox(self.TextTab)
        self.textAlignment_groupBox.setGeometry(QtCore.QRect(340, 250, 251, 111))
        self.textAlignment_groupBox.setObjectName("textAlignment_groupBox")
        self.textRotModeHorizontal = QtWidgets.QRadioButton(self.textAlignment_groupBox)
        self.textRotModeHorizontal.setGeometry(QtCore.QRect(10, 20, 251, 17))
        self.textRotModeHorizontal.setObjectName("textRotModeHorizontal")
        self.textRotModeAligned = QtWidgets.QRadioButton(self.textAlignment_groupBox)
        self.textRotModeAligned.setGeometry(QtCore.QRect(10, 40, 251, 17))
        self.textRotModeAligned.setObjectName("textRotModeAligned")
        self.textRotModeISO = QtWidgets.QRadioButton(self.textAlignment_groupBox)
        self.textRotModeISO.setGeometry(QtCore.QRect(10, 60, 251, 17))
        self.textRotModeISO.setObjectName("textRotModeISO")
        self.textRotModeFixedRot = QtWidgets.QRadioButton(self.textAlignment_groupBox)
        self.textRotModeFixedRot.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.textRotModeFixedRot.setObjectName("textRotModeFixedRot")
        self.textForcedRot = QtWidgets.QDoubleSpinBox(self.textAlignment_groupBox)
        self.textForcedRot.setGeometry(QtCore.QRect(160, 80, 81, 22))
        self.textForcedRot.setDecimals(6)
        self.textForcedRot.setMaximum(360.0)
        self.textForcedRot.setSingleStep(0.0005)
        self.textForcedRot.setObjectName("textForcedRot")
        self.tabWidget.addTab(self.TextTab, "")
        self.AdjustTab = QtWidgets.QWidget()
        self.AdjustTab.setObjectName("AdjustTab")
        self.groupBox_12 = QtWidgets.QGroupBox(self.AdjustTab)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 10, 301, 211))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_35 = QtWidgets.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.textBlockAdjustWhicheverFitsBestOutside = QtWidgets.QRadioButton(self.groupBox_12)
        self.textBlockAdjustWhicheverFitsBestOutside.setGeometry(QtCore.QRect(10, 80, 251, 17))
        self.textBlockAdjustWhicheverFitsBestOutside.setObjectName("textBlockAdjustWhicheverFitsBestOutside")
        self.textBlockAdjustFirstSymbolOutside = QtWidgets.QRadioButton(self.groupBox_12)
        self.textBlockAdjustFirstSymbolOutside.setGeometry(QtCore.QRect(10, 100, 251, 17))
        self.textBlockAdjustFirstSymbolOutside.setObjectName("textBlockAdjustFirstSymbolOutside")
        self.textBlockAdjustFirstTextOutside = QtWidgets.QRadioButton(self.groupBox_12)
        self.textBlockAdjustFirstTextOutside.setGeometry(QtCore.QRect(10, 120, 251, 17))
        self.textBlockAdjustFirstTextOutside.setObjectName("textBlockAdjustFirstTextOutside")
        self.textBlockAdjustBothOutside = QtWidgets.QRadioButton(self.groupBox_12)
        self.textBlockAdjustBothOutside.setGeometry(QtCore.QRect(10, 140, 251, 17))
        self.textBlockAdjustBothOutside.setObjectName("textBlockAdjustBothOutside")
        self.blockSuppressionForNoSpace = QtWidgets.QCheckBox(self.groupBox_12)
        self.blockSuppressionForNoSpace.setGeometry(QtCore.QRect(10, 160, 281, 51))
        self.blockSuppressionForNoSpace.setAutoFillBackground(False)
        self.blockSuppressionForNoSpace.setObjectName("blockSuppressionForNoSpace")
        self.tabWidget.addTab(self.AdjustTab, "")
        self.PrimaryUnitTab = QtWidgets.QWidget()
        self.PrimaryUnitTab.setObjectName("PrimaryUnitTab")
        self.groupBox_13 = QtWidgets.QGroupBox(self.PrimaryUnitTab)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 10, 271, 141))
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_36 = QtWidgets.QLabel(self.groupBox_13)
        self.label_36.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_36.setObjectName("label_36")
        self.textDecimals = QtWidgets.QComboBox(self.groupBox_13)
        self.textDecimals.setGeometry(QtCore.QRect(100, 20, 161, 22))
        self.textDecimals.setObjectName("textDecimals")
        self.textDecimalSep = QtWidgets.QComboBox(self.groupBox_13)
        self.textDecimalSep.setGeometry(QtCore.QRect(170, 50, 91, 22))
        self.textDecimalSep.setObjectName("textDecimalSep")
        self.label_37 = QtWidgets.QLabel(self.groupBox_13)
        self.label_37.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_37.setObjectName("label_37")
        self.textPrefix = QtWidgets.QLineEdit(self.groupBox_13)
        self.textPrefix.setGeometry(QtCore.QRect(110, 80, 151, 20))
        self.textPrefix.setObjectName("textPrefix")
        self.label_38 = QtWidgets.QLabel(self.groupBox_13)
        self.label_38.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_13)
        self.label_39.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.label_39.setObjectName("label_39")
        self.textSuffix = QtWidgets.QLineEdit(self.groupBox_13)
        self.textSuffix.setGeometry(QtCore.QRect(110, 110, 151, 20))
        self.textSuffix.setObjectName("textSuffix")
        self.groupBox_14 = QtWidgets.QGroupBox(self.PrimaryUnitTab)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 160, 271, 51))
        self.groupBox_14.setObjectName("groupBox_14")
        self.textSuppressLeadingZeros = QtWidgets.QCheckBox(self.groupBox_14)
        self.textSuppressLeadingZeros.setGeometry(QtCore.QRect(20, 20, 131, 17))
        self.textSuppressLeadingZeros.setObjectName("textSuppressLeadingZeros")
        self.textDecimalZerosSuppression = QtWidgets.QCheckBox(self.groupBox_14)
        self.textDecimalZerosSuppression.setGeometry(QtCore.QRect(170, 20, 91, 17))
        self.textDecimalZerosSuppression.setObjectName("textDecimalZerosSuppression")
        self.tabWidget.addTab(self.PrimaryUnitTab, "")
        self.layoutWidget = QtWidgets.QWidget(DimStyle_Details_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 410, 239, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.helpButton = QtWidgets.QPushButton(self.layoutWidget)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)

        self.retranslateUi(DimStyle_Details_Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.linearLayerName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.linearLayerNameChanged)
        self.symbolLayerName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.symbolLayerNameChanged)
        self.textualLayerName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.textualLayerNameChanged)
        self.textRotModeFixedRot.toggled['bool'].connect(DimStyle_Details_Dialog.textRotModeFixedRotToggled)
        self.extLineIsFixedLen.toggled['bool'].connect(DimStyle_Details_Dialog.extLineIsFixedLenToggled)
        self.helpButton.clicked.connect(DimStyle_Details_Dialog.ButtonHELP_Pressed)
        self.okButton.clicked.connect(DimStyle_Details_Dialog.accept)
        self.cancelButton.clicked.connect(DimStyle_Details_Dialog.reject)
        self.tabWidget.currentChanged['int'].connect(DimStyle_Details_Dialog.currentTabChanged)
        self.lineTypeFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.linetypeFieldNameChanged)
        self.symbolFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.symbolFieldNameChanged)
        self.scaleFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.scaleFieldNameChanged)
        self.idFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.idFieldNameChanged)
        self.dimStyleFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.dimStyleFieldNameChanged)
        self.dimTypeFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.dimTypeFieldNameChanged)
        self.colorFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.colorFieldNameChanged)
        self.rotFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.rotFieldNameChanged)
        self.componentFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.componentFieldNameChanged)
        self.idParentFieldName.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.idParentFieldNameChanged)
        self.dimLineLineType.textChanged['QString'].connect(DimStyle_Details_Dialog.dimLineLineTypeChanged)
        self.dimLine1Hide.toggled['bool'].connect(DimStyle_Details_Dialog.dimLine1HideToggled)
        self.dimLine2Hide.toggled['bool'].connect(DimStyle_Details_Dialog.dimLine2HideToggled)
        self.extLine1LineType.textChanged['QString'].connect(DimStyle_Details_Dialog.extLine1LineTypeChanged)
        self.extLine2LineType.textChanged['QString'].connect(DimStyle_Details_Dialog.extLine2LineTypeChanged)
        self.extLine1Hide.toggled['bool'].connect(DimStyle_Details_Dialog.extLine1HideToggled)
        self.extLine2Hide.toggled['bool'].connect(DimStyle_Details_Dialog.extLine2HideToggled)
        self.extLineOffsetDimLine.valueChanged['double'].connect(DimStyle_Details_Dialog.extLineOffsetDimLineChanged)
        self.extLineOffsetOrigPoints.valueChanged['double'].connect(DimStyle_Details_Dialog.extLineOffsetOrigPointsChanged)
        self.extLineFixedLen.valueChanged['double'].connect(DimStyle_Details_Dialog.extLineFixedLenChanged)
        self.block1Name.textChanged['QString'].connect(DimStyle_Details_Dialog.block1NameChanged)
        self.block2Name.textChanged['QString'].connect(DimStyle_Details_Dialog.block2NameChanged)
        self.blockLeaderName.textChanged['QString'].connect(DimStyle_Details_Dialog.blockLeaderNameChanged)
        self.blockWidth.valueChanged['double'].connect(DimStyle_Details_Dialog.blockWidthChanged)
        self.blockScale.valueChanged['double'].connect(DimStyle_Details_Dialog.blockScaleChanged)
        self.textFont.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.textFontChanged)
        self.textHeight.valueChanged['double'].connect(DimStyle_Details_Dialog.textHeightChanged)
        self.textVerticalPos.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.textVerticalPosChanged)
        self.textHorizontalPos.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.textHorizontalPosChanged)
        self.textDirection.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.textDirectionChanged)
        self.textOffsetDist.valueChanged['double'].connect(DimStyle_Details_Dialog.textOffsetDistChanged)
        self.textForcedRot.valueChanged['double'].connect(DimStyle_Details_Dialog.textForcedRotChanged)
        self.blockSuppressionForNoSpace.toggled['bool'].connect(DimStyle_Details_Dialog.blockSuppressionForNoSpaceToggled)
        self.textDecimals.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.textDecimalsChanged)
        self.textDecimalSep.currentIndexChanged['int'].connect(DimStyle_Details_Dialog.textDecimalSepChanged)
        self.textPrefix.textChanged['QString'].connect(DimStyle_Details_Dialog.textPrefixChanged)
        self.textSuffix.textChanged['QString'].connect(DimStyle_Details_Dialog.textSuffixChanged)
        self.textSuppressLeadingZeros.toggled['bool'].connect(DimStyle_Details_Dialog.textSuppressLeadingZerosToggled)
        self.textDecimalZerosSuppression.toggled['bool'].connect(DimStyle_Details_Dialog.textDecimalZerosSuppressionToggled)
        self.textRotModeHorizontal.toggled['bool'].connect(DimStyle_Details_Dialog.textRotModeHorizontalToggled)
        self.textRotModeAligned.toggled['bool'].connect(DimStyle_Details_Dialog.textRotModeAlignedToggled)
        self.textRotModeISO.toggled['bool'].connect(DimStyle_Details_Dialog.textRotModeISOToggled)
        self.textBlockAdjustWhicheverFitsBestOutside.toggled['bool'].connect(DimStyle_Details_Dialog.textBlockAdjustWhicheverFitsBestOutsideToggled)
        self.textBlockAdjustFirstSymbolOutside.toggled['bool'].connect(DimStyle_Details_Dialog.textBlockAdjustFirstSymbolOutsideToggled)
        self.textBlockAdjustFirstTextOutside.toggled['bool'].connect(DimStyle_Details_Dialog.textBlockAdjustFirstTextOutsideToggled)
        self.textBlockAdjustBothOutside.toggled['bool'].connect(DimStyle_Details_Dialog.textBlockAdjustBothOutsideToggled)
        self.arcSymbolPreceding.toggled['bool'].connect(DimStyle_Details_Dialog.arcSymbolPrecedingToggled)
        self.arcSymbolAbove.toggled['bool'].connect(DimStyle_Details_Dialog.arcSymbolAboveToggled)
        self.arcSymbolNone.toggled['bool'].connect(DimStyle_Details_Dialog.arcSymbolNoneToggled)
        self.dimLineOffsetExtLine.valueChanged['double'].connect(DimStyle_Details_Dialog.dimLineOffsetExtLineChanged)
        self.centerMarkNone.toggled['bool'].connect(DimStyle_Details_Dialog.centerMarkNoneChanged)
        self.centerMarkMark.toggled['bool'].connect(DimStyle_Details_Dialog.centerMarkMarkChanged)
        self.centerMarkLine.toggled['bool'].connect(DimStyle_Details_Dialog.centerMarkLineChanged)
        self.centerMarkLength.valueChanged['double'].connect(DimStyle_Details_Dialog.centerMarkLengthChanged)
        QtCore.QMetaObject.connectSlotsByName(DimStyle_Details_Dialog)

    def retranslateUi(self, DimStyle_Details_Dialog):
        _translate = QtCore.QCoreApplication.translate
        DimStyle_Details_Dialog.setWindowTitle(_translate("DimStyle_Details_Dialog", "QAD - Dimension style details"))
        self.groupBox_5.setTitle(_translate("DimStyle_Details_Dialog", "Lines"))
        self.label_2.setText(_translate("DimStyle_Details_Dialog", "Layer:"))
        self.linearLayerName.setToolTip(_translate("DimStyle_Details_Dialog", "Name of the layer for dimension lines."))
        self.lineTypeFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the linetype name."))
        self.label_21.setText(_translate("DimStyle_Details_Dialog", "Linetype field:"))
        self.groupBox_6.setTitle(_translate("DimStyle_Details_Dialog", "Symbols and arrows"))
        self.symbolLayerName.setToolTip(_translate("DimStyle_Details_Dialog", "Name of the layer for dimension symbols and arrows."))
        self.label_13.setText(_translate("DimStyle_Details_Dialog", "Layer:"))
        self.label_22.setText(_translate("DimStyle_Details_Dialog", "Symbol field:"))
        self.symbolFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the symbol name."))
        self.scaleFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the symbol size."))
        self.label_23.setText(_translate("DimStyle_Details_Dialog", "Scale field:"))
        self.groupBox_7.setTitle(_translate("DimStyle_Details_Dialog", "Generics fields"))
        self.label_24.setText(_translate("DimStyle_Details_Dialog", "Rotation:"))
        self.rotFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the rotation of the punctual elements od dimension (symbols, arrows, text)."))
        self.label_16.setText(_translate("DimStyle_Details_Dialog", "Color:"))
        self.colorFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the RGB colorfor all elements of dimension (e.g. \"255,255,255,255\" = white with total opacity)."))
        self.label_28.setText(_translate("DimStyle_Details_Dialog", "Linking ID:"))
        self.idParentFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the ID of the dimension to group all elements (except the text which is the root element)."))
        self.label_25.setText(_translate("DimStyle_Details_Dialog", "Component type:"))
        self.componentFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "<html><head/><body><p>Field storing the component type of dimension:</p><p>&quot;D1&quot; = Dimension line 1.</p><p>&quot;D2&quot; = Dimension line 2.</p><p>&quot;E1&quot; = Extension line 1.</p><p>&quot;E2&quot; = Extension line 2.</p><p>&quot;L&quot;  = Leader.</p><p>&quot;B1&quot; = Block 1.</p><p>&quot;B2&quot; = Block 2.</p><p>&quot;LB&quot; = Leader Block.</p><p>&quot;AB&quot; = Arc Block.</p><p>&quot;D1&quot; = Dimension point 1.</p><p>&quot;D2&quot; = Dimension point 2.</p></body></html>"))
        self.groupBox_8.setTitle(_translate("DimStyle_Details_Dialog", "Text"))
        self.label_27.setText(_translate("DimStyle_Details_Dialog", "ID Field:"))
        self.idFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the unique code for each dimension."))
        self.dimStyleFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "Field storing the name of the dimension style."))
        self.label_29.setText(_translate("DimStyle_Details_Dialog", "Dim. style field:"))
        self.label_30.setText(_translate("DimStyle_Details_Dialog", "Dim. type field:"))
        self.dimTypeFieldName.setToolTip(_translate("DimStyle_Details_Dialog", "<html><head/><body><p>Field storing the dimension type:</p><p>&quot;AL&quot; = linear dimension that is aligned with the origin points of the extension lines.</p><p>&quot;AN&quot; = angular dimension, it measures the angle between selected objects or 3 points.</p><p>&quot;BL&quot; = linear, angular, or ordinate dimension from the baseline of the previous or selected dimension.</p><p>&quot;CE&quot; = creates the center mark or the centerlines of circles and arcs.</p><p>&quot;DI&quot; = creates a diameter dimension for a circle or an arc.</p><p>&quot;LD&quot; = creates a line that connects annotation to a feature..</p><p>&quot;LI&quot; = linear dimension with a horizontal, vertical, or rotated dimension line.</p><p>&quot;RA&quot; = radial dimension, measures the radius of a selected circle or arc and displays the dimension text with a radius symbol in front of it.</p><p>&quot;AR&quot; = arc length dimensions measure the distance along an arc or polyline arc segment.</p></body></html>"))
        self.label_14.setText(_translate("DimStyle_Details_Dialog", "Layer:"))
        self.textualLayerName.setToolTip(_translate("DimStyle_Details_Dialog", "Name of the layer storing dimension texts."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DBTab), _translate("DimStyle_Details_Dialog", "DB"))
        self.groupBox.setTitle(_translate("DimStyle_Details_Dialog", "Dimension lines"))
        self.label.setText(_translate("DimStyle_Details_Dialog", "Color:"))
        self.dimLineLineType.setToolTip(_translate("DimStyle_Details_Dialog", "Linetype of dimension line."))
        self.label_3.setText(_translate("DimStyle_Details_Dialog", "Linetype:"))
        self.label_5.setText(_translate("DimStyle_Details_Dialog", "Suppress:"))
        self.dimLine1Hide.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses display of dimension line 1."))
        self.dimLine1Hide.setText(_translate("DimStyle_Details_Dialog", "Dim. line 1"))
        self.dimLine2Hide.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses display of dimension line 2."))
        self.dimLine2Hide.setText(_translate("DimStyle_Details_Dialog", "Dim. line 2"))
        self.label_41.setText(_translate("DimStyle_Details_Dialog", "Extend beyond ticks:"))
        self.dimLineOffsetExtLine.setToolTip(_translate("DimStyle_Details_Dialog", "Specifies a distance to extend the dimension line above the extension lines."))
        self.groupBox_2.setTitle(_translate("DimStyle_Details_Dialog", "Extension lines"))
        self.label_6.setText(_translate("DimStyle_Details_Dialog", "Color:"))
        self.extLine1LineType.setToolTip(_translate("DimStyle_Details_Dialog", "Linetype for extension line 1."))
        self.label_7.setText(_translate("DimStyle_Details_Dialog", "Linetype ext. 1:"))
        self.label_8.setText(_translate("DimStyle_Details_Dialog", "Linetype ext. 2:"))
        self.extLine2LineType.setToolTip(_translate("DimStyle_Details_Dialog", "Linetype for extension line 2."))
        self.label_9.setText(_translate("DimStyle_Details_Dialog", "Suppress:"))
        self.extLine1Hide.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses display of extension line 1."))
        self.extLine1Hide.setText(_translate("DimStyle_Details_Dialog", "Ext. line 1"))
        self.extLine2Hide.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses display of extension line 2."))
        self.extLine2Hide.setText(_translate("DimStyle_Details_Dialog", "Ext. line 2"))
        self.label_10.setText(_translate("DimStyle_Details_Dialog", "Extend beyond dim lines:"))
        self.extLineOffsetDimLine.setToolTip(_translate("DimStyle_Details_Dialog", "Specifies a distance to extend the extension lines above the dimension line."))
        self.extLineOffsetOrigPoints.setToolTip(_translate("DimStyle_Details_Dialog", "Sets the distance to offset the extension lines from the points on the drawing that define the dimension."))
        self.label_11.setText(_translate("DimStyle_Details_Dialog", "Offset from origin:"))
        self.extLineIsFixedLen.setToolTip(_translate("DimStyle_Details_Dialog", "Enables fixed length extension lines."))
        self.extLineIsFixedLen.setText(_translate("DimStyle_Details_Dialog", "Fixed length extension lines"))
        self.label_12.setText(_translate("DimStyle_Details_Dialog", "Length:"))
        self.extLineFixedLen.setToolTip(_translate("DimStyle_Details_Dialog", "Total length of the extension lines starting from the dimension line toward the dimension origin."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LineTab), _translate("DimStyle_Details_Dialog", "Lines"))
        self.groupBox_3.setTitle(_translate("DimStyle_Details_Dialog", "Arrowheads"))
        self.block1Name.setToolTip(_translate("DimStyle_Details_Dialog", "Arrowhead for the first dimension line. When you change the first arrowhead type, the second arrowhead automatically changes to match it."))
        self.label_15.setText(_translate("DimStyle_Details_Dialog", "Arrowhead 1:"))
        self.block2Name.setToolTip(_translate("DimStyle_Details_Dialog", "Arrowhead for the second dimension line."))
        self.label_18.setText(_translate("DimStyle_Details_Dialog", "Arrowhead 2:"))
        self.blockLeaderName.setToolTip(_translate("DimStyle_Details_Dialog", "Arrowhead for the leader line."))
        self.label_19.setText(_translate("DimStyle_Details_Dialog", "Leader:"))
        self.blockWidth.setToolTip(_translate("DimStyle_Details_Dialog", "Arrowhead horizontal size in map units using the symbol scale factor = 1."))
        self.label_17.setText(_translate("DimStyle_Details_Dialog", "Arrowhead size:"))
        self.blockScale.setToolTip(_translate("DimStyle_Details_Dialog", "Arrowhead scale."))
        self.label_20.setText(_translate("DimStyle_Details_Dialog", "Arrowhead scale:"))
        self.groupBox_4.setTitle(_translate("DimStyle_Details_Dialog", "Arc length symbol"))
        self.arcSymbolPreceding.setToolTip(_translate("DimStyle_Details_Dialog", "Places arc length symbols before the dimension text."))
        self.arcSymbolPreceding.setText(_translate("DimStyle_Details_Dialog", "Preceding dimension text"))
        self.arcSymbolAbove.setToolTip(_translate("DimStyle_Details_Dialog", "Places arc length symbols above the dimension text."))
        self.arcSymbolAbove.setText(_translate("DimStyle_Details_Dialog", "Above dimension text"))
        self.arcSymbolNone.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses the display of arc length symbols."))
        self.arcSymbolNone.setText(_translate("DimStyle_Details_Dialog", "None"))
        self.groupBox_11.setTitle(_translate("DimStyle_Details_Dialog", "Center marks"))
        self.centerMarkNone.setToolTip(_translate("DimStyle_Details_Dialog", "Creates no center mark or centerline."))
        self.centerMarkNone.setText(_translate("DimStyle_Details_Dialog", "None"))
        self.centerMarkMark.setToolTip(_translate("DimStyle_Details_Dialog", "Creates a center mark."))
        self.centerMarkMark.setText(_translate("DimStyle_Details_Dialog", "Mark"))
        self.centerMarkLine.setToolTip(_translate("DimStyle_Details_Dialog", "Creates a centerline."))
        self.centerMarkLine.setText(_translate("DimStyle_Details_Dialog", "Line"))
        self.centerMarkLength.setToolTip(_translate("DimStyle_Details_Dialog", "Size of the center mark or centerline."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SymbolTab), _translate("DimStyle_Details_Dialog", "Symbols and arrows"))
        self.groupBox_9.setTitle(_translate("DimStyle_Details_Dialog", "Text appearance"))
        self.label_26.setText(_translate("DimStyle_Details_Dialog", "Text height:"))
        self.textHeight.setToolTip(_translate("DimStyle_Details_Dialog", "Text height in map units."))
        self.label_40.setText(_translate("DimStyle_Details_Dialog", "Character type:"))
        self.textFont.setToolTip(_translate("DimStyle_Details_Dialog", "Dimension text character type."))
        self.label_4.setText(_translate("DimStyle_Details_Dialog", "Color:"))
        self.groupBox_10.setTitle(_translate("DimStyle_Details_Dialog", "Text placement"))
        self.textVerticalPos.setToolTip(_translate("DimStyle_Details_Dialog", "Controls the vertical placement of dimension text in relation to the dimension line."))
        self.label_31.setText(_translate("DimStyle_Details_Dialog", "Vertical:"))
        self.label_32.setText(_translate("DimStyle_Details_Dialog", "Horizontal:"))
        self.textHorizontalPos.setToolTip(_translate("DimStyle_Details_Dialog", "Controls the horizontal placement of dimension text along the dimension line, in relation to the extension lines."))
        self.label_33.setText(_translate("DimStyle_Details_Dialog", "View direction:"))
        self.textDirection.setToolTip(_translate("DimStyle_Details_Dialog", "Controls the dimension text viewing direction."))
        self.textOffsetDist.setToolTip(_translate("DimStyle_Details_Dialog", "Sets the current text gap, which is the distance around the dimension text when the dimension line is broken to accommodate the dimension text."))
        self.label_34.setText(_translate("DimStyle_Details_Dialog", "Offset from dim line:"))
        self.textAlignment_groupBox.setTitle(_translate("DimStyle_Details_Dialog", "Text alignment"))
        self.textRotModeHorizontal.setToolTip(_translate("DimStyle_Details_Dialog", "Places text in a horizontal position."))
        self.textRotModeHorizontal.setText(_translate("DimStyle_Details_Dialog", "Horizontal"))
        self.textRotModeAligned.setToolTip(_translate("DimStyle_Details_Dialog", "Text aligned with Dimension Line."))
        self.textRotModeAligned.setText(_translate("DimStyle_Details_Dialog", "Aligned with dimension line"))
        self.textRotModeISO.setToolTip(_translate("DimStyle_Details_Dialog", "Aligns text with the dimension line when text is inside the extension lines, but aligns it horizontally when text is outside the extension lines."))
        self.textRotModeISO.setText(_translate("DimStyle_Details_Dialog", "ISO Standard"))
        self.textRotModeFixedRot.setToolTip(_translate("DimStyle_Details_Dialog", "Place text with fixed angle."))
        self.textRotModeFixedRot.setText(_translate("DimStyle_Details_Dialog", "Fixed rotation"))
        self.textForcedRot.setToolTip(_translate("DimStyle_Details_Dialog", "Text angle  when fixed rotation mode is on."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TextTab), _translate("DimStyle_Details_Dialog", "Text"))
        self.groupBox_12.setTitle(_translate("DimStyle_Details_Dialog", "Fit options"))
        self.label_35.setText(_translate("DimStyle_Details_Dialog", "If there isn\'t enaugh room to place both text and arrows inside extension lines, the first thing to move outside the extension lines is:"))
        self.textBlockAdjustWhicheverFitsBestOutside.setToolTip(_translate("DimStyle_Details_Dialog", "Moves either the text or the arrowheads outside the extension lines based on the best fit."))
        self.textBlockAdjustWhicheverFitsBestOutside.setText(_translate("DimStyle_Details_Dialog", "Either text or arrows (best fit)"))
        self.textBlockAdjustFirstSymbolOutside.setToolTip(_translate("DimStyle_Details_Dialog", "Moves arrowheads outside the extension lines first, then text."))
        self.textBlockAdjustFirstSymbolOutside.setText(_translate("DimStyle_Details_Dialog", "Arrows"))
        self.textBlockAdjustFirstTextOutside.setToolTip(_translate("DimStyle_Details_Dialog", "Moves text outside the extension lines first, then arrowheads."))
        self.textBlockAdjustFirstTextOutside.setText(_translate("DimStyle_Details_Dialog", "Text"))
        self.textBlockAdjustBothOutside.setToolTip(_translate("DimStyle_Details_Dialog", "When not enough space is available for text and arrowheads, moves both outside the extension lines."))
        self.textBlockAdjustBothOutside.setText(_translate("DimStyle_Details_Dialog", "Both text and arrows"))
        self.blockSuppressionForNoSpace.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses arrowheads if not enough space is available inside the extension lines."))
        self.blockSuppressionForNoSpace.setText(_translate("DimStyle_Details_Dialog", "Suppress arrows if they don\'t fit inside ext. lines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AdjustTab), _translate("DimStyle_Details_Dialog", "Fit"))
        self.groupBox_13.setTitle(_translate("DimStyle_Details_Dialog", "Linear dimensions"))
        self.label_36.setText(_translate("DimStyle_Details_Dialog", "Precision:"))
        self.textDecimals.setToolTip(_translate("DimStyle_Details_Dialog", "Displays and sets the number of decimal places in the dimension text."))
        self.textDecimalSep.setToolTip(_translate("DimStyle_Details_Dialog", "Sets the separator for decimal formats."))
        self.label_37.setText(_translate("DimStyle_Details_Dialog", "Decimal separator:"))
        self.textPrefix.setToolTip(_translate("DimStyle_Details_Dialog", "Includes a prefix that you specify in the dimension text."))
        self.label_38.setText(_translate("DimStyle_Details_Dialog", "Prefix:"))
        self.label_39.setText(_translate("DimStyle_Details_Dialog", "Suffix:"))
        self.textSuffix.setToolTip(_translate("DimStyle_Details_Dialog", "Includes a suffix that you specify in the dimension text."))
        self.groupBox_14.setTitle(_translate("DimStyle_Details_Dialog", "Zero suppression"))
        self.textSuppressLeadingZeros.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses leading zeros in all decimal dimensions (0.5 becomes .5)."))
        self.textSuppressLeadingZeros.setText(_translate("DimStyle_Details_Dialog", "Leading"))
        self.textDecimalZerosSuppression.setToolTip(_translate("DimStyle_Details_Dialog", "Suppresses trailing zeros in all decimal dimensions (5.50 becomes 5.5 and 5.0 becomes 5)."))
        self.textDecimalZerosSuppression.setText(_translate("DimStyle_Details_Dialog", "Trailing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PrimaryUnitTab), _translate("DimStyle_Details_Dialog", "Primary units"))
        self.okButton.setText(_translate("DimStyle_Details_Dialog", "OK"))
        self.cancelButton.setText(_translate("DimStyle_Details_Dialog", "Cancel"))
        self.helpButton.setText(_translate("DimStyle_Details_Dialog", "?"))

