# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QAD(object):
    def setupUi(self, QAD):
        QAD.setObjectName("QAD")
        QAD.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(QAD)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(QAD)
        self.buttonBox.accepted.connect(QAD.accept)
        self.buttonBox.rejected.connect(QAD.reject)
        QtCore.QMetaObject.connectSlotsByName(QAD)

    def retranslateUi(self, QAD):
        _translate = QtCore.QCoreApplication.translate
        QAD.setWindowTitle(_translate("QAD", "QAD"))
