# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qad_tooltip_appearance.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ToolTipAppearance_Dialog(object):
    def setupUi(self, ToolTipAppearance_Dialog):
        ToolTipAppearance_Dialog.setObjectName("ToolTipAppearance_Dialog")
        ToolTipAppearance_Dialog.resize(379, 366)
        ToolTipAppearance_Dialog.setMinimumSize(QtCore.QSize(379, 366))
        ToolTipAppearance_Dialog.setMaximumSize(QtCore.QSize(379, 366))
        self.widget_Preview = QtWidgets.QWidget(ToolTipAppearance_Dialog)
        self.widget_Preview.setGeometry(QtCore.QRect(20, 20, 191, 71))
        self.widget_Preview.setObjectName("widget_Preview")
        self.Button_TooltipColors = QtWidgets.QPushButton(ToolTipAppearance_Dialog)
        self.Button_TooltipColors.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.Button_TooltipColors.setObjectName("Button_TooltipColors")
        self.groupBox = QtWidgets.QGroupBox(ToolTipAppearance_Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 351, 51))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 351, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.edit_size = QtWidgets.QLineEdit(self.groupBox_2)
        self.edit_size.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.edit_size.setObjectName("edit_size")
        self.slider_size = QtWidgets.QSlider(self.groupBox_2)
        self.slider_size.setGeometry(QtCore.QRect(130, 20, 211, 22))
        self.slider_size.setPageStep(1)
        self.slider_size.setOrientation(QtCore.Qt.Horizontal)
        self.slider_size.setObjectName("slider_size")
        self.groupBox_3 = QtWidgets.QGroupBox(ToolTipAppearance_Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 190, 351, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.slider_transparency = QtWidgets.QSlider(self.groupBox_3)
        self.slider_transparency.setGeometry(QtCore.QRect(130, 20, 211, 22))
        self.slider_transparency.setOrientation(QtCore.Qt.Horizontal)
        self.slider_transparency.setObjectName("slider_transparency")
        self.edit_transparency = QtWidgets.QLineEdit(self.groupBox_3)
        self.edit_transparency.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.edit_transparency.setObjectName("edit_transparency")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ToolTipAppearance_Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 330, 251, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_OK = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_OK.setObjectName("Button_OK")
        self.horizontalLayout.addWidget(self.Button_OK)
        self.Button_Cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.horizontalLayout.addWidget(self.Button_Cancel)
        self.Button_Help = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_Help.setObjectName("Button_Help")
        self.horizontalLayout.addWidget(self.Button_Help)
        self.groupBox_4 = QtWidgets.QGroupBox(ToolTipAppearance_Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 250, 351, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radio_for_all_tooltips = QtWidgets.QRadioButton(self.groupBox_4)
        self.radio_for_all_tooltips.setGeometry(QtCore.QRect(20, 20, 321, 17))
        self.radio_for_all_tooltips.setObjectName("radio_for_all_tooltips")
        self.radio_for_DI_tooltips = QtWidgets.QRadioButton(self.groupBox_4)
        self.radio_for_DI_tooltips.setGeometry(QtCore.QRect(20, 40, 321, 17))
        self.radio_for_DI_tooltips.setObjectName("radio_for_DI_tooltips")

        self.retranslateUi(ToolTipAppearance_Dialog)
        self.Button_TooltipColors.clicked.connect(ToolTipAppearance_Dialog.Button_TooltipColors_Pressed)
        self.Button_Cancel.clicked.connect(ToolTipAppearance_Dialog.reject)
        self.slider_size.valueChanged['int'].connect(ToolTipAppearance_Dialog.slider_size_moved)
        self.edit_size.textChanged['QString'].connect(ToolTipAppearance_Dialog.edit_size_textChanged)
        self.edit_transparency.textChanged['QString'].connect(ToolTipAppearance_Dialog.edit_transparency_textChanged)
        self.slider_transparency.valueChanged['int'].connect(ToolTipAppearance_Dialog.slider_transparency_moved)
        self.Button_OK.clicked.connect(ToolTipAppearance_Dialog.ButtonBOX_Accepted)
        self.Button_Help.clicked.connect(ToolTipAppearance_Dialog.ButtonHELP_Pressed)
        QtCore.QMetaObject.connectSlotsByName(ToolTipAppearance_Dialog)

    def retranslateUi(self, ToolTipAppearance_Dialog):
        _translate = QtCore.QCoreApplication.translate
        ToolTipAppearance_Dialog.setWindowTitle(_translate("ToolTipAppearance_Dialog", "QAD - Tooltip appearance"))
        self.Button_TooltipColors.setToolTip(_translate("ToolTipAppearance_Dialog", "Displays the Drawing Window Colors dialog box, where you can specify a color for drafting tooltips and their backgrounds in a specified context."))
        self.Button_TooltipColors.setText(_translate("ToolTipAppearance_Dialog", "Colors..."))
        self.groupBox.setTitle(_translate("ToolTipAppearance_Dialog", "Size"))
        self.groupBox_2.setTitle(_translate("ToolTipAppearance_Dialog", "Size"))
        self.edit_size.setToolTip(_translate("ToolTipAppearance_Dialog", "Specifies a size for tooltips. The default size is 0. Use the slider to make tooltips larger or smaller."))
        self.slider_size.setToolTip(_translate("ToolTipAppearance_Dialog", "Specifies a size for tooltips. The default size is 0. Use the slider to make tooltips larger or smaller."))
        self.groupBox_3.setTitle(_translate("ToolTipAppearance_Dialog", "Transparency"))
        self.slider_transparency.setToolTip(_translate("ToolTipAppearance_Dialog", "Controls the transparency of tooltips. The lower the setting, the less transparent the tooltip. A value of 0 sets the tooltip to opaque."))
        self.edit_transparency.setToolTip(_translate("ToolTipAppearance_Dialog", "Controls the transparency of tooltips. The lower the setting, the less transparent the tooltip. A value of 0 sets the tooltip to opaque."))
        self.Button_OK.setText(_translate("ToolTipAppearance_Dialog", "OK"))
        self.Button_Cancel.setText(_translate("ToolTipAppearance_Dialog", "Cancel"))
        self.Button_Help.setText(_translate("ToolTipAppearance_Dialog", "?"))
        self.groupBox_4.setTitle(_translate("ToolTipAppearance_Dialog", "Apply to:"))
        self.radio_for_all_tooltips.setText(_translate("ToolTipAppearance_Dialog", "Override OS settings for all drafting tooltips"))
        self.radio_for_DI_tooltips.setText(_translate("ToolTipAppearance_Dialog", "Use settings only for Dynamic Input tooltips"))

