######################################################################
# Automatically generated by qmake (2.01a) lun 25. nov 08:34:04 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ..\
INCLUDEPATH += ..\

# Input
FORMS += ..\*.ui
RESOURCES += ..\qad.qrc
SOURCES += ..\*.py

TRANSLATIONS += qad_it.ts \
                qad_fi.ts \
                qad_es.ts

CODECFORSRC = UTF-8
CODECFORTR = UTF-8